export const ActionTypes = {
  CREATE_FLASH_MESSAGE: 'CREATE_FLASH_MESSAGE',
  SWITCH_LOGIN: 'SWITCH_LOGIN',
  SEARCH_TOGGLE: 'SEARCH_TOGGLE',
  CHAT_TOGGLE: 'CHAT_TOGGLE',
  INCREMENT_UNREAD_MESSAGES: 'INCREMENT_UNREAD_MESSAGES',
  CLEAR_UNREAD_MESSAGES: 'CLEAR_UNREAD_MESSAGES',
};
